version: '3'
services:
  db:
    image: postgres:15.5
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - '3001:3001'

    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  postgresql-data:
    driver: local