databases:
  - name: pairdev_database
    databaseName: pairdev_database_0bbi
    user: pairdev_database_0bbi_user
    region: singapore

services:
  - type: web
    name: pairdev
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pairdev_database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false