import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextAuthProvider from '@/providers/NextAuth';
import Header from './components/Header';
import Footer from './components/Footer';
import { Poppins } from "next/font/google";
const HachiMaruPopFont = Poppins({ weight: "500", subsets: ["latin"] });

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${HachiMaruPopFont.className} flex flex-col min-h-screen`}>
        <NextAuthProvider>
          <Header />
            <main className="flex-1">
              {children}
            </main>
          <Footer />
        </NextAuthProvider>
      </body>
    </html>
  )
}
